import type { Config } from 'tailwindcss';
import { heroui } from '@heroui/react';

const config: Config = {
  content: [
    './app/**/*.{ts,tsx,js,jsx,html}',
    './components/**/*.{ts,tsx,js,jsx}',
    // HeroUI v2 components (autogenerated paths)
    './node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}',
  ],
  // HeroUI uses prefixed classes (e.g. `data-[hover=true]:bg-default-100`)
  // and the prefix "heroui-" is added by the plugin when imported. Setting
  // `prefix` here would conflict with our existing non-prefixed utility
  // classes, so we keep the default (no prefix) — the plugin's own
  // prefixed classes still work because the plugin emits non-prefixed
  // selectors internally.
  theme: {
    extend: {
      // 2GIS-inspired light palette. Crisp white surfaces, soft gray neutrals,
      // warm red accent for "live"/interactive elements, deep navy text.
      colors: {
        // Neutrals (page background → cards → text)
        surface: {
          DEFAULT: '#f5f6f8',  // page background
          card: '#ffffff',      // panels & cards
          hover: '#f0f2f5',     // hover state
        },
        line: {
          DEFAULT: '#e6e8ec',   // dividers
          strong: '#d0d3da',    // stronger borders
        },
        ink: {
          900: '#1c1c21',       // primary text
          700: '#3a3a44',       // body text
          500: '#6b6b75',       // secondary text
          400: '#9090a0',       // tertiary text / hints
          300: '#b5b5be',       // muted
        },
        // 2GIS-style red
        brand: {
          50:  '#fff1f0',
          100: '#ffe1de',
          400: '#f5575d',
          500: '#e63946',       // primary red
          600: '#cc2e3b',       // hover
          700: '#a82230',
        },
        // Semantic accents
        accent: {
          orange: '#f5a524',    // "warning" — price increased
          green:  '#0fa968',    // "success" — price decreased, active deal
          red:    '#e63946',    // brand
          yellow: '#f5a524',
        },
        // HeroUI default tokens — we re-map them onto our 2GIS palette
        // so HeroUI's components (Input, Button, Drawer, Popover) look
        // native to this app instead of bringing the default blue.
        default: {
          50:  '#ffffff',
          100: '#f5f6f8',
          200: '#eceef2',
          300: '#d8dbe1',
          400: '#b5b5be',
          500: '#9090a0',
          600: '#6b6b75',
          700: '#3a3a44',
          800: '#25252b',
          900: '#1c1c21',
          foreground: '#1c1c21',
          DEFAULT: '#ffffff',
        },
        primary: {
          50:  '#fff1f0',
          100: '#ffe1de',
          200: '#ffc1bb',
          300: '#ff9991',
          400: '#f5575d',
          500: '#e63946',
          600: '#cc2e3b',
          700: '#a82230',
          800: '#841a25',
          900: '#5e111a',
          foreground: '#ffffff',
          DEFAULT: '#e63946',
        },
        success: {
          500: '#0fa968',
          DEFAULT: '#0fa968',
        },
        warning: {
          500: '#f5a524',
          DEFAULT: '#f5a524',
        },
        danger: {
          500: '#e63946',
          DEFAULT: '#e63946',
        },
        background: '#f5f6f8',
        foreground: '#1c1c21',
        divider: '#e6e8ec',
        focus: '#e63946',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['"Space Grotesk"', 'Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      boxShadow: {
        // Subtle, refined — 2GIS-style depth
        card:    '0 1px 2px rgba(15,18,28,0.04), 0 1px 3px rgba(15,18,28,0.06)',
        'card-lg': '0 2px 4px rgba(15,18,28,0.05), 0 8px 24px rgba(15,18,28,0.08)',
        panel:   '0 4px 12px rgba(15,18,28,0.06), 0 16px 40px rgba(15,18,28,0.10)',
        marker:  '0 2px 6px rgba(15,18,28,0.30)',
        glow:    '0 0 0 1px rgba(230,57,70,0.30), 0 6px 18px -4px rgba(230,57,70,0.45)',
      },
      borderRadius: {
        '2xs': '4px',
      },
      animation: {
        'fade-in': 'fadeIn .25s ease-out',
        'slide-in': 'slideIn .3s cubic-bezier(.2,.7,.2,1)',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
        'pulse-red': 'pulseRed 1.6s ease-out infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideIn: {
          '0%': { transform: 'translateX(20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        pulseSoft: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(230,57,70,0.45)' },
          '50%':      { boxShadow: '0 0 0 8px rgba(230,57,70,0)' },
        },
        pulseRed: {
          '0%':   { boxShadow: '0 0 0 0 rgba(230,57,70,0.55)' },
          '70%':  { boxShadow: '0 0 0 6px rgba(230,57,70,0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(230,57,70,0)' },
        },
      },
    },
  },
  darkMode: 'class',
  // heroui() expands into a set of default variants (size, color, …) the
  // component classes need. Keep it last so it can see the colors above.
  plugins: [heroui({
    themes: {
      light: {
        colors: {
          background: '#f5f6f8',
          foreground: '#1c1c21',
          divider: '#e6e8ec',
          focus: '#e63946',
        },
      },
    },
  })],
};
export default config;
